# .github/workflows/deploy.yml
name: Deploy SimpleBoard

on: workflow_dispatch

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  VPS_IP: ${{ secrets.VPS_IP }}
  VPS_USER: root
  VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
  APP_DIR: "/home/root/app"
  ENVIRONMENT: ${{ github.event.inputs.environment || 'prod' }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Dev
        if: env.ENVIRONMENT == 'dev'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USER }}
          key: ${{ env.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ${{ env.APP_DIR }}
            docker login -u ${{ env.DOCKER_HUB_USERNAME }} --password ${{ env.DOCKER_HUB_TOKEN }}
            docker-compose pull
            docker-compose down
            docker-compose up -d

      - name: Deploy to Prod
        if: env.ENVIRONMENT == 'prod'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USER }}
          key: ${{ env.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ${{ env.APP_DIR }}
            docker login -u ${{ env.DOCKER_HUB_USERNAME }} --password ${{ env.DOCKER_HUB_TOKEN }}
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d
